net:
  cpus: 1
  encoder_depth: 5
  encoder_name: efficientnet-b4
  encoder_weights: imagenet
  epochs: 50
  gpus: 2
  learning_rate: 0.001
  n_channels: 3
  n_classes: 4
  scheduler_factor: 0.2
  scheduler_patience: 20
  segmentation_model: unet++
  train_batches: 32
  val_batches: 8
wholeslidedata:
  default:
    annotation_sources:
      filters:
      - xml
    associations:
      exact_match: true
    batch_shape:
      batch_size: 32
      shape:
      - 512
      - 512
      - 3
      spacing: 1
    label_map:
      hgd-g: 3
      lgd-g: 2
      ndbe-g: 1
    point_sampler:
      attribute: RandomPointSampler
    seed: 3
    yaml_source: /home/mbotros/code/barrett_gland_grading/configs/split.yml
  training:
    batch_callbacks:
    - attribute: AlbumentationsAugmentationsCallback
      augmentations:
      - RandomRotate90:
          p: 0.5
      - Flip:
          p: 0.5
      - RandomGamma:
          gamma_limit:
          - 50
          - 100
          p: 0.5
      - ColorJitter:
          brightness: 0.1
          contrast: 0.1
          hue: 0.1
          p: 0.5
          saturation: 0.1
      module: wholeslidedata.accessories.albumentations.callbacks
